backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "shows"
    label: "Cartelera de Shows"
    folder: "src/content/shows"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Nombre del Evento", name: "title", widget: "string" }
      - { label: "Fecha (Ej: SAB 15 MAR)", name: "date", widget: "string" }
      - { label: "Lugar / Estadio", name: "location", widget: "string", hint: "Ej: Movistar Arena" }
      - { label: "Imagen del Flyer", name: "image", widget: "image" }
      - { label: "Link de Entradas", name: "link", widget: "string", required: false }
      - { label: "Descripción del Show", name: "body", widget: "markdown", hint: "Detalles adicionales, line-up, etc." }